return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  opts = {
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
    folds = { enable = true },
    ensure_installed = {
      "bash",
      "embedded_template",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "ruby",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "zsh",
    },
  }
}
